services:
  api_gateway_nest:
    build: ./http-api-gateway-nest
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway-nest/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
    restart: always
  hello_nest_microservice:
    build: ./hello-nest-microservice
    volumes:
      - ./hello-nest-microservice/src:/usr/src/app/src
    command: yarn start:dev
  hello_rust_microservice:
    build: ./hello-rust-microservice
    volumes:
      - ./hello-rust-microservice:/app
    command: sh -c "cargo watch -x run"
  nats:
    image: nats:latest
    command: --js --debug --trace --sd /data -p 4222 -m 8222
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    restart: always
    volumes:
      - ./jetstream-cluster/n1:/data
  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: "-connz -varz -channelz -serverz -subz -healthz -routez http://nats:8222"
    ports:
      - "7777:7777"
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3030:3000"